// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqpaozbujmuplfyzzxiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxcGFvemJ1am11cGxmeXp6eGl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MzAyNjYsImV4cCI6MjA2NjQwNjI2Nn0.hq6dg2YguoeE6SLtp7rQX2inM2WRNX3Eh8D1TPM14tM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);